import type { Lesson } from "./types";

export const MORE_LESSONS: Lesson[] = [
  {
    id: 7,
    pos: 7,
    slug: "uniform-exponential",
    tier: 2,
    title: "Uniform and Exponential — the two continuous workhorses",
    sub: "Equally likely between L and U, or time until the next event. Memoryless is a favourite trap.",
    lastPaper: 2,
    older: 2,
    recipe: "Uniform: P = length / (U−L).  Exponential: P(X > x) = e^{−λx}.",
    body: [
      {
        type: "h",
        text: "Uniform — every value between L and U is equally likely",
      },
      {
        type: "formula",
        title: "Uniform(L, U)",
        lines: [
          "f(x) = 1 / (U − L)     for L ≤ x ≤ U",
          "P(a < X < b) = (b − a) / (U − L)     (clip to [L,U] first)",
          "E[X] = (L + U) / 2",
          "Var(X) = (U − L)² / 12",
        ],
      },
      {
        type: "p",
        text: "To find the k-th percentile, solve (x − L)/(U − L) = k. So the 80th percentile is L + 0.80(U − L).",
      },
      {
        type: "callout",
        kind: "example",
        title: "Worked — a parcel equally likely to arrive between day 2 and day 8",
        text: "L=2, U=8. P(arrives before day 5) = (5−2)/(8−2) = 3/6 = **0.50**.\nMean wait = (2+8)/2 = 5 days. Var = 36/12 = 3.",
      },
      {
        type: "h",
        text: "Exponential — the waiting-time machine",
      },
      {
        type: "p",
        text: "Models the **time between** independent events that arrive at a constant rate λ. Battery life, time to the next customer, time to failure.",
      },
      {
        type: "formula",
        title: "Exponential(λ)",
        lines: [
          "f(x) = λ e^{−λx}     x ≥ 0",
          "P(X ≤ x) = 1 − e^{−λx}",
          "P(X > x) = e^{−λx}          ← the one they actually ask",
          "Mean = SD = 1/λ         Var = 1/λ²",
        ],
      },
      {
        type: "callout",
        kind: "recipe",
        title: "Memoryless — say it in English first",
        text: "P(X > t₀ + t | X > t₀) = P(X > t).\nThe process forgets how long you have already waited. If the mean wait is 10 minutes and you have already waited 8, the remaining wait is still Exponential with mean 10. This is the favourite trick question on the paper.",
      },
      {
        type: "callout",
        kind: "tip",
        title: "Poisson counts, Exponential times",
        text: "Same process. If events arrive at λ = 6 per hour, the count in one hour is Poisson(6), and the wait between events is Exponential(6) with mean 10 minutes.",
      },
    ],
    questions: [
      {
        id: "7a",
        story: "A technician arrives equally likely any time between 1pm and 5pm.",
        prompt: "P(she arrives between 2pm and 3pm) is",
        options: ["0.20", "0.25", "0.33", "0.50"],
        answer: 1,
        explain: "Window length 1 hour, total length 4 hours. 1/4 = **0.25**. Uniform probability is just length over length.",
        src: "exam",
      },
      {
        id: "7b",
        story: "Customers arrive at 3 per hour (Poisson process).",
        prompt: "P(you wait more than 20 minutes for the next one) is closest to",
        options: ["0.05", "0.22", "0.37", "0.50"],
        answer: 2,
        explain: "Wait ~ Exponential(λ=3 per hour). 20 min = 1/3 hour. P(X>1/3) = e^{−3·1/3} = e^{−1} ≈ **0.368**.",
        src: "exam",
      },
      {
        id: "7c",
        prompt: "A component's lifetime is exponential with mean 10 hours. It has already run 7 hours. The expected remaining life is",
        options: ["3 hours", "7 hours", "10 hours", "17 hours"],
        answer: 2,
        explain: "**Memoryless.** Remaining life is still Exponential with mean 10. The 7 hours already burned do not shorten the remaining expectation.",
        src: "exam",
      },
      {
        id: "7d",
        story: "X ~ Uniform(0, 50). Find the 80th percentile.",
        prompt: "P_80 equals",
        options: ["40", "45", "50", "80"],
        answer: 0,
        explain: "Solve (x − L)/(U − L) = 0.80. x = 0 + 0.80×50 = **40**. Uniform percentiles are just a fraction of the way along the interval.",
        src: "exam",
      },
      {
        id: "7e",
        story: "Wait ~ Exponential, mean 5 minutes.",
        prompt: "P(wait > 5 minutes) is closest to",
        options: ["0.37", "0.50", "0.63", "e^{−5}"],
        answer: 0,
        explain: "λ = 1/5. P(X>5) = e^{−λ·5} = e^{−1} ≈ **0.368**. Mean wait does **not** mean 50% chance of beating it — exponential is right-skewed.",
        src: "exam",
      },
    ],
  },
  {
    id: 8,
    pos: 8,
    slug: "linear-combo",
    tier: 2,
    title: "Linear combinations — scale, shift, add, average",
    sub: "Means add. Variances add only if independent. The minus sign still adds variance.",
    lastPaper: 2,
    older: 2,
    recipe: "E[aX+b] = aE[X]+b.  Var(aX+b) = a² Var(X).  For independent sums, variances add.",
    body: [
      {
        type: "p",
        text: "Almost every 'combined' question on this paper is one of three shapes: scale-and-shift one variable, add two variables, or average n identical copies.",
      },
      {
        type: "formula",
        title: "One variable, Y = aX + b",
        lines: [
          "E[Y] = a E[X] + b          (shift and scale both move the mean)",
          "Var(Y) = a² Var(X)         (the +b vanishes; a is squared)",
          "SD(Y) = |a| · SD(X)",
        ],
      },
      {
        type: "formula",
        title: "Two variables, Y = X₁ + X₂",
        lines: [
          "E[Y] = E[X₁] + E[X₂]                         always",
          "Var(Y) = Var(X₁) + Var(X₂) + 2 Cov(X₁,X₂)",
          "If independent, Cov = 0, so variances just add.",
        ],
      },
      {
        type: "callout",
        kind: "trap",
        title: "Difference still adds variance",
        text: "Y = X₁ − X₂ is Y = (1)X₁ + (−1)X₂. The −1 squares to +1. So Var(X₁ − X₂) = Var(X₁) + Var(X₂) when independent. Subtracting does **not** cancel risk.",
      },
      {
        type: "formula",
        title: "n independent identical copies",
        lines: [
          "Sum S:     E[S] = nμ      SD(S) = √n · σ",
          "Average X̄: E[X̄] = μ       SD(X̄) = σ / √n",
          "The mean of the average stays put. The spread shrinks as n grows.",
        ],
      },
      {
        type: "callout",
        kind: "example",
        title: "Worked — converting Celsius, then averaging",
        text: "Each day's temperature X has mean 20 and SD 4. Y = 1.8X + 32 (Fahrenheit).\nE[Y] = 1.8×20 + 32 = 68.  SD(Y) = 1.8×4 = 7.2.\nAverage of 16 independent days: SD(X̄) = 4/√16 = 1.",
      },
    ],
    questions: [
      {
        id: "8a",
        story: "X has mean 10 and variance 4. Y = 3X − 6.",
        prompt: "E[Y] and Var(Y) are",
        options: ["24 and 12", "24 and 36", "30 and 36", "24 and 4"],
        answer: 1,
        explain: "E[Y] = 3×10 − 6 = **24**. Var(Y) = 9 × 4 = **36**. The −6 does nothing to variance.",
        src: "exam",
      },
      {
        id: "8b",
        story: "Independent X and Y, Var(X)=9, Var(Y)=16.",
        prompt: "SD(X − Y) is",
        options: ["1", "5", "7", "25"],
        answer: 1,
        explain: "Var(X−Y) = 9+16 = 25. SD = **5**. The minus does not subtract the variances.",
        src: "exam",
      },
      {
        id: "8c",
        story: "i.i.d. daily sales, mean 50, SD 8. You average n = 16 days.",
        prompt: "SD of the average is",
        options: ["0.5", "2", "8", "32"],
        answer: 1,
        explain: "σ/√n = 8/4 = **2**. The mean of the average is still 50 — they didn't ask for that.",
        src: "exam",
      },
      {
        id: "8d",
        story: "Independent X, Y. E[X]=2, E[Y]=5, Var(X)=9, Var(Y)=16.",
        prompt: "E[3X − Y] and Var(3X − Y) are",
        options: ["1 and 7", "1 and 97", "11 and 25", "1 and 65"],
        answer: 1,
        explain: "E = 3×2 − 5 = **1**. Var = 9×9 + 16 = 81+16 = **97**. The minus still **adds** variance; 3 is squared.",
        src: "exam",
      },
      {
        id: "8e",
        prompt: "n i.i.d. copies. As n grows, the SD of the average",
        options: ["Stays σ", "Grows like √n", "Shrinks like 1/√n", "Becomes nσ"],
        answer: 2,
        explain: "SD(X̄) = σ/√n. **Shrinks.** The mean of the average stays μ. That is why averaging n days of sales calms the wobble.",
        src: "concept",
      },
    ],
  },
  {
    id: 9,
    pos: 9,
    slug: "portfolio",
    tier: 2,
    title: "Two-asset portfolio — the risk-reduction machine",
    sub: "Weighted average of returns. Negative correlation is how you actually reduce risk.",
    lastPaper: 2,
    older: 1,
    recipe: "E[Z]=w₁E[X]+w₂E[Y].  Var(Z)=w₁²σ_X² + w₂²σ_Y² + 2w₁w₂ Cov.",
    body: [
      {
        type: "p",
        text: "Put weight w₁ on asset X and w₂ on asset Y (usually w₁ + w₂ = 1). The portfolio return is Z = w₁X + w₂Y. This is just the linear combination from Lesson 8, with extra vocabulary.",
      },
      {
        type: "formula",
        title: "The two formulas, written the way the paper writes them",
        lines: [
          "E[Z] = w₁ E[X] + w₂ E[Y]",
          "Var(Z) = w₁² σ_X² + w₂² σ_Y² + 2 w₁ w₂ Cov(X,Y)",
          "Cov(X,Y) = r · σ_X · σ_Y",
          "r = Cov / (σ_X σ_Y)     correlation, always between −1 and +1",
        ],
      },
      {
        type: "callout",
        kind: "recipe",
        title: "Risk reduction in one sentence",
        text: "A **negative** correlation makes the last term negative, which **shrinks** portfolio variance. That is diversification. Two assets that zip up together (r near +1) do not diversify anything.",
      },
      {
        type: "callout",
        kind: "example",
        title: "Worked — 60% in X, 40% in Y, r = −0.3",
        text: "E[X]=0.12, E[Y]=0.08, σ_X=0.20, σ_Y=0.10.\nE[Z] = 0.6(0.12)+0.4(0.08) = 0.104.\nCov = −0.3×0.20×0.10 = −0.006.\nVar(Z) = (0.6)²(0.04) + (0.4)²(0.01) + 2(0.6)(0.4)(−0.006)\n= 0.0144 + 0.0016 − 0.00288 = 0.01312.\nSD(Z) ≈ 0.115.",
      },
      {
        type: "callout",
        kind: "trap",
        title: "Weights on the SD, not the SD of the weights",
        text: "You square the **weights**, you do not take w × σ and then square the sum. Write the formula down before touching a calculator.",
      },
    ],
    questions: [
      {
        id: "9a",
        story: "w₁=0.5, w₂=0.5, E[X]=10%, E[Y]=6%.",
        prompt: "Portfolio expected return is",
        options: ["6%", "8%", "10%", "16%"],
        answer: 1,
        explain: "0.5×10 + 0.5×6 = **8%**. Means weight. No covariance needed for the mean.",
        src: "exam",
      },
      {
        id: "9b",
        prompt: "Two assets have σ_X = 4, σ_Y = 3, Cov(X,Y) = −6. Correlation r is",
        options: ["−0.50", "−0.40", "0.40", "0.50"],
        answer: 0,
        explain: "r = Cov/(σ_X σ_Y) = −6 / 12 = **−0.50**. Negative: they move against each other.",
        src: "exam",
      },
      {
        id: "9c",
        prompt: "Which change most reliably cuts portfolio SD, holding weights fixed?",
        options: [
          "Raising both means",
          "Pushing correlation from +0.8 toward −0.8",
          "Making both SDs equal",
          "Setting w₁ = 1",
        ],
        answer: 1,
        explain: "The covariance term is 2w₁w₂rσ_Xσ_Y. Making **r more negative** subtracts more from Var(Z). Putting all weight on one asset (w₁=1) *removes* diversification.",
        src: "concept",
      },
    ],
  },
  {
    id: 10,
    pos: 10,
    slug: "conditional-bayes",
    tier: 2,
    title: "Conditional probability and Bayes — the update machine",
    sub: "Given that. The most English-looking questions on the paper, and the most missed.",
    lastPaper: 2,
    older: 2,
    recipe: "P(A|B) = P(A ∩ B)/P(B).  Bayes: posterior = joint / evidence.",
    body: [
      {
        type: "p",
        text: "Conditional probability is 'of the world where B already happened, what fraction is also A'. The formula is a division, not a new idea.",
      },
      {
        type: "formula",
        title: "The four lines that run the whole topic",
        lines: [
          "P(A|B) = P(A ∩ B) / P(B)",
          "P(A ∩ B) = P(B) · P(A|B)     (multiplication law)",
          "Independent: P(A|B) = P(A), so P(A ∩ B) = P(A)P(B)",
          "Bayes: P(A|B) = P(B|A) P(A) / P(B)",
        ],
      },
      {
        type: "p",
        text: "**Prior** P(A) is your belief before the new information. **Posterior** P(A|B) is the belief after. Bayes is just the multiplication law, rearranged so you can update.",
      },
      {
        type: "callout",
        kind: "example",
        title: "Worked — a factory test",
        text: "1% of parts are defective. A test catches a defective 99% of the time, but false-alarms on 5% of good parts. A part tests positive. P(it is actually defective)?\n\nP(D) = 0.01, P(Dᶜ)=0.99.\nP(+ ∩ D) = 0.01 × 0.99 = 0.0099.\nP(+ ∩ Dᶜ) = 0.99 × 0.05 = 0.0495.\nP(+) = 0.0594.\nP(D|+) = 0.0099 / 0.0594 ≈ **0.167**.\n\nMost people guess 99%. The test is noisy enough, and defects are rare enough, that a positive is still probably a false alarm.",
      },
      {
        type: "callout",
        kind: "tip",
        title: "Draw the two-by-two",
        text: "Rows = truth (A / Aᶜ). Columns = evidence (B / Bᶜ). Fill the four joints. The posterior is one joint divided by its column total. If you can fill the table, you cannot get Bayes wrong.",
      },
    ],
    questions: [
      {
        id: "10a",
        story: "P(A)=0.4, P(B)=0.5, P(A ∩ B)=0.2.",
        prompt: "P(A|B) is",
        options: ["0.20", "0.40", "0.50", "0.80"],
        answer: 1,
        explain: "0.2 / 0.5 = **0.40**. Same as P(A), so A and B are independent in this particular table — coincidence, not a rule.",
        src: "exam",
      },
      {
        id: "10b",
        story: "2% of users churn. A warning model flags 80% of churners and 10% of stayers.",
        prompt: "Given a flag, P(the user will churn) is closest to",
        options: ["0.08", "0.14", "0.80", "0.90"],
        answer: 1,
        explain: "P(flag ∩ churn) = 0.02×0.80 = 0.016. P(flag ∩ stay) = 0.98×0.10 = 0.098. P(flag)=0.114. Posterior = 0.016/0.114 ≈ **0.140**.",
        src: "exam",
      },
      {
        id: "10c",
        prompt: "Two events with P(A)>0 and P(B)>0 cannot be both mutually exclusive and independent. Why?",
        options: [
          "Because then P(A ∪ B) would exceed 1",
          "Mutually exclusive ⇒ P(A ∩ B)=0, but independent ⇒ P(A ∩ B)=P(A)P(B)>0",
          "Independence requires P(A)=P(B)",
          "They can — the statement is false",
        ],
        answer: 1,
        explain: "**Contradiction.** Exclusive means the intersection is empty (probability 0). Independent means the intersection is the product of the two probabilities, which is positive. Pick one.",
        src: "concept",
      },
      {
        id: "10d",
        story: "P(Rain)=0.2, P(umbrella | rain)=0.9, P(umbrella | no rain)=0.3.",
        prompt: "P(it is raining | you see an umbrella) is closest to",
        options: ["0.20", "0.43", "0.90", "0.30"],
        answer: 1,
        explain: "P(U ∩ R)=0.2×0.9=0.18. P(U ∩ Rᶜ)=0.8×0.3=0.24. P(U)=0.42. Posterior = 0.18/0.42 ≈ **0.429**. Most umbrellas you see are still on dry days.",
        src: "exam",
      },
      {
        id: "10e",
        story: "P(A)=0.5, P(B)=0.4, A and B independent.",
        prompt: "P(A|B) is",
        options: ["0.2", "0.4", "0.5", "0.9"],
        answer: 2,
        explain: "Independence means P(A|B)=P(A)=**0.5**. The 'given B' does not change A.",
        src: "exam",
      },
    ],
  },
  {
    id: 11,
    pos: 11,
    slug: "probability-laws",
    tier: 3,
    title: "The four probability laws — complement, union, exclusive, independent",
    sub: "Cheap marks if you can tell exclusive apart from independent.",
    lastPaper: 1,
    older: 2,
    recipe: "P(Aᶜ)=1−P(A).  P(A∪B)=P(A)+P(B)−P(A∩B).  Exclusive: intersection 0. Independent: product.",
    body: [
      {
        type: "p",
        text: "A **random experiment** has more than one possible outcome. The **sample space** S is the full list. An **event** is a subset. Probabilities live in [0, 1] and the whole of S sums to 1.",
      },
      {
        type: "formula",
        title: "Four laws, in the order you will use them",
        lines: [
          "Complement:   P(Aᶜ) = 1 − P(A)",
          "Addition:     P(A ∪ B) = P(A) + P(B) − P(A ∩ B)",
          "Exclusive:    P(A ∩ B) = 0, so P(A ∪ B) = P(A) + P(B)",
          "Independent:  P(A ∩ B) = P(A) P(B)",
        ],
      },
      {
        type: "table",
        headers: ["Word", "English", "Math"],
        rows: [
          ["Union ∪", "A or B or both", "add, then subtract the overlap"],
          ["Intersection ∩", "A and B", "the overlap"],
          ["Mutually exclusive", "cannot happen together", "overlap is 0"],
          ["Independent", "one does not change the other", "overlap is the product"],
        ],
      },
      {
        type: "callout",
        kind: "trap",
        title: "Exclusive is not independent",
        text: "If two events cannot happen together, learning that A happened *does* change P(B) — it drops to 0. That is the opposite of independence. This is asked, in words, almost every paper.",
      },
    ],
    questions: [
      {
        id: "11a",
        story: "P(A)=0.6, P(B)=0.5, P(A ∩ B)=0.3.",
        prompt: "P(A ∪ B) is",
        options: ["0.3", "0.6", "0.8", "1.1"],
        answer: 2,
        explain: "0.6+0.5−0.3 = **0.8**. If you forget to subtract the intersection you get 1.1, which is an illegal probability — instant red flag.",
        src: "exam",
      },
      {
        id: "11b",
        prompt: "P(A) = 0.3. P(Aᶜ) is",
        options: ["0.3", "0.7", "1.3", "0"],
        answer: 1,
        explain: "1 − 0.3 = **0.7**. Complement is the cheapest mark on the paper.",
        src: "concept",
      },
      {
        id: "11c",
        prompt: "Events A and B are mutually exclusive, P(A)=0.4, P(B)=0.2. P(A ∩ B) is",
        options: ["0", "0.08", "0.6", "0.08 or 0, depending"],
        answer: 0,
        explain: "**0.** Exclusive means they share no outcomes. 0.08 would be the independent answer, which this is not.",
        src: "exam",
      },
      {
        id: "11d",
        story: "P(A)=0.4, P(B)=0.5, A and B independent.",
        prompt: "P(A ∪ B) is",
        options: ["0.2", "0.7", "0.9", "1.0"],
        answer: 1,
        explain: "Intersection = 0.4×0.5 = 0.2. Union = 0.4+0.5−0.2 = **0.7**. Adding to 0.9 forgets to subtract the overlap.",
        src: "exam",
      },
      {
        id: "11e",
        prompt: "P(A ∪ B) comes out 1.2. That means",
        options: [
          "The events are independent",
          "You forgot to subtract P(A ∩ B), because a probability cannot exceed 1",
          "The events are exclusive",
          "You should divide by 1.2",
        ],
        answer: 1,
        explain: "**Illegal probability.** Union without subtracting the intersection is the usual way to blow past 1.",
        src: "concept",
      },
    ],
  },
  {
    id: 12,
    pos: 12,
    slug: "variance-cv",
    tier: 3,
    title: "Variance, SD, CV — three ways to say 'spread'",
    sub: "s² is in squared units. s is in the original units. CV is a percentage, so you can compare.",
    lastPaper: 1,
    older: 1,
    recipe: "s² = Σ(x−x̄)² / (n−1).  s = √s².  CV = (s / x̄) × 100.",
    body: [
      {
        type: "p",
        text: "**Range** is max − min: two points, allergic to outliers. **IQR** is Q3 − Q1: the middle 50%, robust. When they want a single number for spread of a sample, they want **sample variance** and **sample SD**.",
      },
      {
        type: "formula",
        title: "Sample, not population — the n−1",
        lines: [
          "s² = Σ (xᵢ − x̄)²  /  (n − 1)     ← degrees of freedom",
          "s  = √s²                            ← same units as the data",
          "CV = (s / x̄) × 100%                ← unit-free, comparable",
        ],
      },
      {
        type: "callout",
        kind: "tip",
        title: "When to reach for CV",
        text: "Comparing Apple's stock-price wobble to P&G's. Different means, different rupee levels. CV puts both on a percent scale. Bigger CV = relatively more variable.",
      },
      {
        type: "callout",
        kind: "trap",
        title: "n vs n−1",
        text: "The paper wants the **sample** versions: VAR.S, STDEV.S, divisor n−1. If they ever say 'population of these 5 numbers', then divide by n. They almost never do.",
      },
    ],
    questions: [
      {
        id: "12a",
        story: "Two numbers: 2 and 6. Sample.",
        prompt: "Sample variance s² is",
        options: ["4", "8", "16", "2"],
        answer: 1,
        explain: "Mean = 4. Deviations −2 and +2, squares 4 and 4, sum 8. Divide by n−1 = 1, so **s² = 8**. s = √8 ≈ 2.83. If you divided by n you got 4 — that is the population version.",
        src: "exam",
      },
      {
        id: "12b",
        story: "Series A: mean 50, s = 10. Series B: mean 200, s = 20.",
        prompt: "Which is relatively more variable?",
        options: ["A (CV 20%)", "B (CV 10%)", "They are equal", "Cannot say without n"],
        answer: 0,
        explain: "CV_A = 10/50 = **20%**. CV_B = 20/200 = 10%. A wobbles more *relative to its level*, even though B's raw SD is larger.",
        src: "exam",
      },
      {
        id: "12c",
        prompt: "Range is a poor spread measure because",
        options: [
          "It uses only two points and is wrecked by one outlier",
          "It requires a normal population",
          "It cannot be computed for even n",
          "It always equals the IQR",
        ],
        answer: 0,
        explain: "**Two points, allergic to outliers.** IQR exists specifically to ignore the tails.",
        src: "concept",
      },
      {
        id: "12d",
        story: "Sample variance s² = 25 rupees-squared.",
        prompt: "The sample standard deviation is",
        options: ["5 rupees-squared", "5 rupees", "25 rupees", "√25 percent"],
        answer: 1,
        explain: "s = √25 = **5**, and it comes back into the **original units** (rupees). Variance stays squared. That is why they prefer to report s.",
        src: "exam",
      },
      {
        id: "12e",
        story: "The three numbers 1, 2, 3.",
        prompt: "Sample variance s² equals",
        options: ["2/3", "1", "2", "4"],
        answer: 1,
        explain: "Mean = 2. Squared deviations 1 + 0 + 1 = 2. Divide by n−1 = 2, so **s² = 1**. Population variance would be 2/3 — the paper wants n−1 unless it says 'these are the whole population'.",
        src: "exam",
      },
      {
        id: "12f",
        story: "Fund A: mean return 8%, s = 4%. Fund B: mean 20%, s = 6%.",
        prompt: "By CV, which is riskier per unit of return?",
        options: ["A (CV 50%)", "B (CV 30%)", "B, because its s is larger", "They are equally risky"],
        answer: 0,
        explain: "CV_A = 4/8 = **50%**. CV_B = 6/20 = 30%. A wobbles more relative to what it earns. Raw SD lies here because B's mean is bigger.",
        src: "exam",
      },
    ],
  },
  {
    id: 13,
    pos: 13,
    slug: "z-outliers",
    tier: 3,
    title: "Z-scores and the ±3 outlier rule",
    sub: "Standardise, then read. |z| > 3 is the flag.",
    lastPaper: 1,
    older: 1,
    recipe: "z = (x − mean) / s.  Mean 0, SD 1 after.  |z|>3 → outlier.",
    body: [
      {
        type: "p",
        text: "A z-score answers 'how many standard deviations is this value from the mean?'. After you convert every point to z, the new list has mean 0 and SD 1. That is **standardisation**.",
      },
      {
        type: "formula",
        title: "The conversion",
        lines: [
          "z = (x − x̄) / s          (sample)",
          "z = (x − μ) / σ           (population / a named distribution)",
          "Excel: =STANDARDIZE(x, mean, standard_dev)",
        ],
      },
      {
        type: "callout",
        kind: "recipe",
        title: "The ±3 rule",
        text: "Any point with z < −3 or z > +3 is treated as an **outlier**. This is a different rule from the box-plot fences (those use 1.5×IQR). The paper will tell you which one it wants by the words it uses: 'z-score' vs 'box plot' / 'fences'.",
      },
      {
        type: "callout",
        kind: "example",
        title: "Worked",
        text: "x = 85, mean = 70, s = 5.  z = (85−70)/5 = 3.0. Sitting exactly on the fence. Usually they still want you to flag |z| ≥ 3 as an outlier; if both 3.0 and 'not quite' appear, pick the option that says z = 3.",
      },
    ],
    questions: [
      {
        id: "13a",
        story: "Exam scores: mean 60, s = 8. A student scores 84.",
        prompt: "z is",
        options: ["1.5", "2.0", "3.0", "24"],
        answer: 2,
        explain: "(84−60)/8 = 24/8 = **3.0**. Three SDs above the mean.",
        src: "exam",
      },
      {
        id: "13b",
        prompt: "After standardising a list, the new mean and SD are",
        options: ["mean 0, SD 1", "mean 1, SD 0", "unchanged", "mean 0, SD s"],
        answer: 0,
        explain: "**Mean 0, SD 1.** That is the definition of a z-score list.",
        src: "concept",
      },
      {
        id: "13c",
        prompt: "Which z-score is an outlier by the z-rule?",
        options: ["z = 1.96", "z = 2.5", "z = −3.2", "z = 0"],
        answer: 2,
        explain: "|−3.2| = 3.2 > 3.  1.96 is the 95% normal critical value, not an outlier threshold.",
        src: "exam",
      },
      {
        id: "13d",
        story: "Mean 100, s = 10. A point has z = −1.5.",
        prompt: "The original value x is",
        options: ["85", "98.5", "115", "−15"],
        answer: 0,
        explain: "x = mean + z·s = 100 + (−1.5)×10 = 100 − 15 = **85**. Rearrange z = (x−mean)/s when they give you z and ask for x.",
        src: "exam",
      },
      {
        id: "13e",
        prompt: "A value with z = 3.0, by the z-outlier rule, is",
        options: [
          "Not an outlier — you need |z| > 3",
          "On the boundary, treated as an outlier (|z| ≥ 3)",
          "An outlier only if the box-plot fence agrees",
          "Impossible, z cannot equal 3",
        ],
        answer: 1,
        explain: "The notes flag |z| greater than 3. On a 4-option MCQ, **z = 3 sits on the fence** and they want it called an outlier. Don't overthink the equality.",
        src: "exam",
      },
      {
        id: "13f",
        prompt: "The z-outlier rule and the 1.5×IQR fence",
        options: [
          "Always flag the same points",
          "Are two different recipes — use the one the question names",
          "Are identical once you standardise",
          "Cannot both appear on the same paper",
        ],
        answer: 1,
        explain: "**Different recipes.** z uses mean and s (pulled by outliers). Fences use quartiles (robust). If the stem says 'z-score', do not reach for 1.5×IQR.",
        src: "concept",
      },
    ],
  },
  {
    id: 14,
    pos: 14,
    slug: "center",
    tier: 3,
    title: "Mean, median, mode — pick the right centre",
    sub: "Mean for symmetric. Median for skewed (income, house prices). Mode for the most common label.",
    lastPaper: 1,
    older: 1,
    recipe: "Sort for the median. Mean = Σx/n. Mode = most frequent.",
    body: [
      {
        type: "p",
        text: "Three centres, three jobs. The paper's favourite move is to hand you a list with one huge outlier and ask which measure 'best represents' the data.",
      },
      {
        type: "table",
        headers: ["Measure", "How", "Weakness", "Use when"],
        rows: [
          ["Mean", "Σx / n", "Pulled by outliers", "Symmetric, no monsters"],
          ["Median", "Middle of the sorted list", "Ignores magnitude in the tails", "Skewed: income, prices"],
          ["Mode", "Most frequent value", "May not exist, or there may be several", "Categories, 'most common'"],
        ],
      },
      {
        type: "p",
        text: "Odd n: the exact middle. Even n: average the two middle values. **Weighted mean** is Σ wᵢ xᵢ / Σ wᵢ — use it when some observations matter more (credit hours, portfolio weights, class sizes).",
      },
      {
        type: "formula",
        title: "Weighted mean — two classes, one number",
        lines: [
          "x̄_w = (n₁ x̄₁ + n₂ x̄₂) / (n₁ + n₂)",
          "Or in weights: (Σ wᵢ xᵢ) / (Σ wᵢ)",
          "A common trap is averaging the two means 50-50 when the groups have different sizes.",
        ],
      },
      {
        type: "callout",
        kind: "recipe",
        title: "Skew pulls the mean toward the tail",
        text: "Right tail (income, house prices): mean > median. Left tail (easy exam with a few zeros): mean < median. Mode sits at the peak. Unimodal = one peak, bimodal = two, multimodal = more. Categories love the mode; numbers with a monster outlier love the median.",
      },
      {
        type: "callout",
        kind: "example",
        title: "Worked — 12, 15, 18, 20, 90",
        text: "Mean = 155/5 = **31** (the 90 dragged it). Median = **18**. Mode = none. If they ask for a 'typical' salary-like number, 18 is the honest answer.",
      },
      {
        type: "p",
        text: "Excel: =AVERAGE, =MEDIAN, =MODE.SNGL / MODE.MULT. You will not be tested on the Excel names, but they are in the notes.",
      },
    ],
    questions: [
      {
        id: "14a",
        story: "Incomes: 20, 22, 25, 27, 80 (lakhs).",
        prompt: "The most honest typical income is",
        options: ["The mean, 34.8", "The median, 25", "The mode, 20", "The range, 60"],
        answer: 1,
        explain: "Right-skewed with a single rich outlier. **Median 25.** The mean 34.8 pretends the typical person earns more than four of the five people.",
        src: "exam",
      },
      {
        id: "14b",
        prompt: "n = 6 sorted values. The median is",
        options: [
          "The 3rd value",
          "The 4th value",
          "The average of the 3rd and 4th",
          "The average of all six",
        ],
        answer: 2,
        explain: "Even n: average the two middle observations — positions **3 and 4**.",
        src: "concept",
      },
      {
        id: "14c",
        story: "Section A mean 70 with 20 students. Section B mean 90 with 30 students.",
        prompt: "Combined mean is closest to",
        options: ["80", "82", "85", "90"],
        answer: 1,
        explain: "Weighted mean = (20×70 + 30×90) / 50 = (1400+2700)/50 = 4100/50 = **82**.",
        src: "exam",
      },
      {
        id: "14d",
        prompt: "The list 2, 2, 5, 5, 9 is",
        options: ["Unimodal with mode 2", "Bimodal with modes 2 and 5", "Multimodal", "Has no mode"],
        answer: 1,
        explain: "**Bimodal.** 2 and 5 both appear twice, 9 once. Two peaks of equal height.",
        src: "concept",
      },
      {
        id: "14e",
        prompt: "A histogram of exam scores has a long left tail (a few zeros). Then",
        options: [
          "Mean > median, report the mean",
          "Mean < median, report the median",
          "Mean = mode = median",
          "The mean is the most honest centre",
        ],
        answer: 1,
        explain: "**Left-skewed.** The tail of zeros drags the mean **down** below the median. Report the median.",
        src: "exam",
      },
      {
        id: "14f",
        story: "A shop sells 40% of units at ₹10 and 60% at ₹20.",
        prompt: "The weighted mean price is",
        options: ["₹14", "₹15", "₹16", "₹18"],
        answer: 2,
        explain: "0.40×10 + 0.60×20 = 4 + 12 = **₹16**. Averaging 10 and 20 to get 15 pretends the two prices sold equally.",
        src: "exam",
      },
    ],
  },
  {
    id: 15,
    pos: 15,
    slug: "percentiles-box",
    tier: 3,
    title: "Percentiles, quartiles, IQR, and box-plot fences",
    sub: "The Unit 1 recipe they hide in the formula sheet. Location, then interpolate. Then the box.",
    lastPaper: 2,
    older: 2,
    recipe: "L_p = (p/100)(n+1). If that is not a whole number, walk the fraction of the way from one sorted value to the next.",
    body: [
      {
        type: "p",
        text: "The p-th **percentile** is a number sitting in the sorted list such that **at least p% of the observations are at or below it**. That is a position in the ordered data, not a percentage of the values themselves. 40th percentile ≠ '40% of the mean'.",
      },
      {
        type: "h",
        text: "Quartiles are just named percentiles",
      },
      {
        type: "table",
        headers: ["Name", "Percentile", "What it cuts"],
        rows: [
          ["Q1, first quartile", "25th", "Bottom 25% below it"],
          ["Q2, second quartile", "50th = median", "Half below, half above"],
          ["Q3, third quartile", "75th", "Top 25% above it"],
        ],
      },
      {
        type: "formula",
        title: "The two-step recipe — location, then interpolate",
        lines: [
          "1. Sort the n numbers. Never skip this.",
          "2. Location  L_p = (p / 100) × (n + 1)     ← Excel PERCENTILE.EXC",
          "3. If L_p is a whole number k, the percentile is the k-th sorted value.",
          "4. If L_p = k + d  (k whole, d a fraction), walk d of the way from the k-th value to the (k+1)-th:",
          "      value = x_{(k)}  +  d × (x_{(k+1)} − x_{(k)})",
        ],
      },
      {
        type: "callout",
        kind: "example",
        title: "Worked — n = 9, find Q1, median, Q3",
        text: "Sorted: 6, 7, 8, 10, 12, 14, 15, 18, 20.   n+1 = 10.\n\nQ1: L_25 = 0.25 × 10 = **2.5**. Between the 2nd (7) and 3rd (8).\n7 + 0.5×(8−7) = **7.5**.\n\nMedian: L_50 = 0.50 × 10 = **5**. The 5th value = **12**.\n\nQ3: L_75 = 0.75 × 10 = **7.5**. Between the 7th (15) and 8th (18).\n15 + 0.5×(18−15) = **16.5**.\n\nIQR = 16.5 − 7.5 = **9**.\nLower fence = 7.5 − 1.5×9 = **−6**. Upper = 16.5 + 13.5 = **30**.\nEvery point here sits inside. No outliers on the box plot.",
      },
      {
        type: "callout",
        kind: "trap",
        title: "Three ways this mark is lost",
        text: "Using n instead of n+1. Forgetting to **sort**. Treating L_p = 2.5 as 'the 2nd value' instead of interpolating. The fraction is the whole point of the question.",
      },
      {
        type: "formula",
        title: "Five-number summary and the box",
        lines: [
          "Min, Q1, Median, Q3, Max",
          "The box runs from Q1 to Q3. The line inside is the median, never the mean.",
          "IQR = Q3 − Q1     (middle 50%, robust to outliers)",
          "Lower fence = Q1 − 1.5 × IQR",
          "Upper fence = Q3 + 1.5 × IQR",
          "Whiskers stop at the last actual data point still inside the fences.",
          "Points outside the fences are plotted as dots. Those are the outliers.",
        ],
      },
      {
        type: "callout",
        kind: "tip",
        title: "Open Solve → Percentile · quartiles",
        text: "Paste the list, type 25 or 40 or 75. It sorts, finds L_p, interpolates, and prints the five-number summary plus the fences. Use it to check every Unit 1 arithmetic question.",
      },
    ],
    questions: [
      {
        id: "15a",
        story: "Q1 = 10, Q3 = 22.",
        prompt: "The upper fence is",
        options: ["22", "28", "34", "40"],
        answer: 3,
        explain: "IQR = 12. Upper = 22 + 1.5×12 = 22+18 = **40**.",
        src: "exam",
      },
      {
        id: "15b",
        prompt: "n = 19. Location of the 40th percentile L_40 is",
        options: ["7.6", "8.0", "8.4", "40"],
        answer: 1,
        explain: "L_p = (p/100)(n+1) = 0.40 × 20 = **8**. The 8th sorted value (no interpolation needed).",
        src: "exam",
      },
      {
        id: "15c",
        prompt: "On a box plot, the line inside the box is",
        options: ["The mean", "The mode", "The median (Q2)", "The midrange"],
        answer: 2,
        explain: "**Median.** The box itself runs from Q1 to Q3. The mean is not part of the five-number summary.",
        src: "concept",
      },
      {
        id: "15d",
        story: "Sorted n = 9: 6, 7, 8, 10, 12, 14, 15, 18, 20.",
        prompt: "Q1 (25th percentile) is",
        options: ["6", "7", "7.5", "8"],
        answer: 2,
        explain: "L_25 = 0.25 × 10 = 2.5. Between the 2nd (7) and 3rd (8): 7 + 0.5×(8−7) = **7.5**. If you grabbed the 2nd value and stopped, that is the trap.",
        src: "exam",
      },
      {
        id: "15e",
        story: "Same list. Q1 = 7.5, Q3 = 16.5.",
        prompt: "A point at 20 on this box plot is",
        options: [
          "An outlier — it is the maximum",
          "Inside the fences, so a regular whisker point",
          "Below the lower fence",
          "Exactly on the upper fence",
        ],
        answer: 1,
        explain: "IQR = 9. Upper fence = 16.5 + 13.5 = **30**. 20 < 30, so it is **inside**. The max being 20 does not make it an outlier. Whisker goes out to 20.",
        src: "exam",
      },
      {
        id: "15f",
        story: "Sorted n = 8: 3, 5, 6, 8, 10, 12, 14, 20.",
        prompt: "The 40th percentile is closest to",
        options: ["6.0", "7.2", "8.0", "8.4"],
        answer: 1,
        explain: "L_40 = 0.40 × 9 = **3.6**. Between the 3rd (6) and 4th (8): 6 + 0.6×(8−6) = 6 + 1.2 = **7.2**.",
        src: "exam",
      },
      {
        id: "15g",
        prompt: "The whisker of a box plot extends",
        options: [
          "All the way to the fence, even if no data is there",
          "To the last actual observation still inside the fence",
          "To the mean",
          "Always to min and max, outliers included",
        ],
        answer: 1,
        explain: "**Last inside point.** Fences are invisible calculation lines. Whiskers stop at real data. Outliers sit past the whisker as dots.",
        src: "concept",
      },
      {
        id: "15h",
        prompt: "IQR is preferred to the range as a spread measure because",
        options: [
          "It uses every observation",
          "It is the middle 50% and ignores the extreme tails",
          "It equals the standard deviation",
          "It requires the data to be normal",
        ],
        answer: 1,
        explain: "**Middle 50%.** One monster salary wrecks the range (max−min) and the mean; IQR barely moves.",
        src: "concept",
      },
    ],
  },
  {
    id: 16,
    pos: 16,
    slug: "scales",
    tier: 3,
    title: "Data types and scales — the 30-second classifier",
    sub: "Nominal, ordinal, interval, ratio. One definition question, one free mark.",
    lastPaper: 1,
    older: 1,
    recipe: "Names → nominal. Ordered names → ordinal. Number, fake zero → interval. Number, true zero → ratio.",
    body: [
      {
        type: "p",
        text: "An **element** is the entity (a customer, a firm). A **variable** is a characteristic of that entity. An **observation** is one row. **Cross-sectional** data is a snapshot; **time series** is the same thing tracked over time. **Observational** studies watch; **experiments** (A/B tests) poke.",
      },
      {
        type: "table",
        headers: ["Scale", "What it is", "Examples", "Math you are allowed"],
        rows: [
          ["Nominal", "Label, no order", "Gender, region, store ID", "Count, mode"],
          ["Ordinal", "Label with order", "S / M / L, satisfaction", "Count, median, rank"],
          ["Interval", "Number, zero is arbitrary", "°C, calendar year, SAT", "Add/subtract, mean. No ratios."],
          ["Ratio", "Number, zero means none", "Income, age, price, weight", "Everything, including 'twice as'"],
        ],
      },
      {
        type: "callout",
        kind: "trap",
        title: "Temperature is the classic interval example",
        text: "0°C is not 'no temperature'. 20°C is not twice 10°C. Kelvin would be ratio. Calendar years are interval for the same reason: year 0 is a convention.",
      },
      {
        type: "p",
        text: "Charts in one line: **bar** (gaps) for categories, **histogram** (bars touch) for quantitative, **scatter** for two quantitative, **pie** only if you enjoy being wrong — they are hard to compare.",
      },
    ],
    questions: [
      {
        id: "16a",
        prompt: "Customer satisfaction recorded as Dissatisfied / Neutral / Satisfied is",
        options: ["Nominal", "Ordinal", "Interval", "Ratio"],
        answer: 1,
        explain: "**Ordinal.** Labels with a built-in rank. No honest 'how much more'.",
        src: "exam",
      },
      {
        id: "16b",
        prompt: "Which of these is ratio-scale?",
        options: ["SAT score", "Celsius temperature", "Year of founding", "Monthly sales in rupees"],
        answer: 3,
        explain: "**Sales.** Zero means no sales, and ₹200 is twice ₹100. SAT and °C are interval; year is interval.",
        src: "exam",
      },
      {
        id: "16c",
        prompt: "A histogram is the right picture for",
        options: [
          "Store names",
          "A quantitative variable's distribution",
          "Two categorical variables",
          "A pie of one number",
        ],
        answer: 1,
        explain: "**Quantitative frequency distribution.** Bars touch to show continuity. Categories get a bar chart with gaps.",
        src: "concept",
      },
      {
        id: "16d",
        prompt: "Jersey numbers on a cricket team (7, 10, 18) are",
        options: ["Ratio — 18 is twice 9", "Interval — zero is arbitrary", "Ordinal — 18 is better than 7", "Nominal — labels that happen to be digits"],
        answer: 3,
        explain: "**Nominal.** The number is a name. 18 is not 'twice as much player' as 9. Same trap as ID numbers and phone numbers.",
        src: "exam",
      },
      {
        id: "16e",
        prompt: "A 5-point Likert item (Strongly disagree → Strongly agree) is",
        options: ["Nominal", "Ordinal", "Interval", "Ratio"],
        answer: 1,
        explain: "**Ordinal.** Ordered labels. The gap from 1 to 2 is not guaranteed to equal the gap from 4 to 5, so it is not interval.",
        src: "exam",
      },
      {
        id: "16f",
        prompt: "Which statement is true?",
        options: [
          "0°C means 'no temperature', so Celsius is ratio",
          "Year 2000 is twice year 1000 in a meaningful sense",
          "₹0 sales means no sales, so rupees are ratio",
          "Store IDs can be averaged",
        ],
        answer: 2,
        explain: "**Sales.** Absolute zero, ratios allowed. Celsius and calendar years are interval. Store IDs are nominal — averaging them is nonsense.",
        src: "exam",
      },
    ],
  },
  {
    id: 17,
    pos: 17,
    slug: "pictures-of-data",
    tier: 3,
    title: "Pictures of data — frequency, charts, study types",
    sub: "The notes' first ten pages. One definition question, one free mark if you can name the picture.",
    lastPaper: 1,
    older: 1,
    recipe: "Count → frequency. Divide by n → relative. ×100 → percent. Then pick the chart that matches the data type.",
    body: [
      {
        type: "p",
        text: "An **element** is the entity you collected data on (a customer, a store). A **variable** is a characteristic of that entity. An **observation** is one row. A **data set** is the whole table.",
      },
      {
        type: "table",
        headers: ["Phrase", "What it is", "Example"],
        rows: [
          ["Cross-sectional", "Snapshot at one moment", "January satisfaction survey, Census 2020"],
          ["Time series", "Same thing tracked over time", "Monthly sales for 3 years, daily stock prices"],
          ["Observational", "Watch, don't poke", "Count customers walking in"],
          ["Experimental / A/B", "You manipulate a variable", "Half the site gets a new button"],
        ],
      },
      {
        type: "formula",
        title: "Three columns of a frequency table",
        lines: [
          "Frequency          = count in that class",
          "Relative frequency = frequency / n",
          "Percent frequency  = relative frequency × 100",
        ],
      },
      {
        type: "table",
        headers: ["Picture", "Use it for", "Giveaway"],
        rows: [
          ["Bar chart", "Categories (nominal/ordinal)", "Bars do **not** touch"],
          ["Pie chart", "Share of a whole", "Hard to compare slices — they discourage it"],
          ["Histogram", "One quantitative variable", "Bars **touch** (continuity)"],
          ["Scatter plot", "Two quantitative variables", "Each point is a pair (x, y)"],
          ["Side-by-side bar", "Compare a category across groups", "Satisfaction by gender"],
          ["Stacked bar", "Composition of the whole", "Each bar sums to 100%"],
        ],
      },
      {
        type: "callout",
        kind: "recipe",
        title: "Skewness in one glance",
        text: "A histogram with a long **right** tail is right-skewed: mean > median (income, prices). A long **left** tail is left-skewed: mean < median. Symmetric: mean ≈ median ≈ mode. That is the only reason they show you a histogram and then ask which centre to report.",
      },
    ],
    questions: [
      {
        id: "17a",
        prompt: "Daily closing prices of a stock for 250 trading days is",
        options: [
          "Cross-sectional observational data",
          "Time-series data",
          "An experiment",
          "Ordinal categorical data",
        ],
        answer: 1,
        explain: "**Time series.** Same variable, many time points. A one-day snapshot of many stocks would be cross-sectional.",
        src: "exam",
      },
      {
        id: "17b",
        story: "A café logs 40 customers: 10 espresso, 18 filter, 12 other.",
        prompt: "The relative frequency of filter coffee is",
        options: ["18", "0.18", "0.45", "45"],
        answer: 2,
        explain: "18/40 = **0.45**. Percent frequency would be 45%. Relative frequency is the fraction, not the count.",
        src: "exam",
      },
      {
        id: "17c",
        prompt: "A histogram of incomes has a long tail to the right. Which is true?",
        options: [
          "Mean < median, report the mean",
          "Mean > median, report the median",
          "Mean = median, either is fine",
          "The mode is larger than both",
        ],
        answer: 1,
        explain: "**Right-skewed.** The tail pulls the mean up past the median. Income and house prices: report the **median**.",
        src: "exam",
      },
      {
        id: "17d",
        prompt: "To compare satisfaction (Low / Med / High) across men and women, the right picture is",
        options: [
          "A pie of all six combinations",
          "A histogram",
          "A side-by-side bar chart",
          "A scatter plot",
        ],
        answer: 2,
        explain: "**Side-by-side bar.** One categorical breakdown, split by a second category. Stacked bar if you want composition of the whole. Scatter needs two quantitative axes.",
        src: "exam",
      },
      {
        id: "17e",
        prompt: "A researcher randomly assigns half the website visitors a new checkout button. This is",
        options: [
          "An observational study",
          "Cross-sectional data only, not a study type",
          "An experiment (A/B test)",
          "Time-series data",
        ],
        answer: 2,
        explain: "**Experiment.** You manipulated a variable. Counting who already used the old button, without assigning it, would be observational.",
        src: "exam",
      },
      {
        id: "17f",
        story: "A frequency table: 8 of 32 customers chose Store A.",
        prompt: "Percent frequency of Store A is",
        options: ["0.25", "8", "25%", "32%"],
        answer: 2,
        explain: "Relative frequency = 8/32 = 0.25. Percent frequency = 0.25 × 100 = **25%**. Don't mix the three columns.",
        src: "exam",
      },
    ],
  },
  {
    id: 18,
    pos: 18,
    slug: "pmf-cdf-pdf",
    tier: 3,
    title: "PMF, CDF, PDF — the three letters they mix up",
    sub: "Discrete gets a mass. Continuous gets a density. Exact values of a continuous RV have probability zero.",
    lastPaper: 1,
    older: 1,
    recipe: "Discrete: f(x)=P(X=x), sum to 1. Continuous: area under f(x). CDF F(x)=P(X≤x). Tail = 1−F(x).",
    body: [
      {
        type: "p",
        text: "A **random variable** is a number attached to an outcome. **Discrete** RVs take countable values (defects, customers, orders). **Continuous** RVs take any value in an interval (time, weight, temperature).",
      },
      {
        type: "formula",
        title: "Discrete — probability mass function",
        lines: [
          "f(x) = P(X = x)          0 ≤ f(x) ≤ 1",
          "Σ f(x) = 1",
          "F(x) = P(X ≤ x)          = sum of the masses up to x   (CDF)",
          "P(X > x) = 1 − F(x)      tail",
        ],
      },
      {
        type: "formula",
        title: "Continuous — probability density function",
        lines: [
          "f(x) is a density, not a probability.  f(x) ≥ 0.  Total area = 1.",
          "P(a < X < b) = area under f between a and b.",
          "P(X = any exact number) = 0.     So P(X ≤ x) = P(X < x).",
          "F(x) = P(X ≤ x) = area from the left end up to x.",
        ],
      },
      {
        type: "callout",
        kind: "trap",
        title: "The favourite trick on continuous questions",
        text: "They ask P(X = 12) for a waiting time or a weight. The answer is **0**. Probability lives on intervals, not points. That also means you can drop the equal sign: P(X ≥ 10) = P(X > 10) for any continuous RV.",
      },
      {
        type: "callout",
        kind: "tip",
        title: "How to tell them apart on the paper",
        text: "**Counts** (0, 1, 2, …) → PMF, add the masses. **Measurements** (time, kg, rupees as a continuous amount) → PDF, find an area. Uniform, exponential, normal are PDFs. Bernoulli, binomial, Poisson are PMFs.",
      },
    ],
    questions: [
      {
        id: "18a",
        prompt: "Delivery time X is continuous. P(X = 30 minutes) is",
        options: ["The height of the PDF at 30", "1/30", "0", "F(30)"],
        answer: 2,
        explain: "**0.** A continuous RV puts probability on intervals, never on a single point. The PDF height is a density, not a probability.",
        src: "exam",
      },
      {
        id: "18b",
        story: "A discrete RV has F(3) = P(X ≤ 3) = 0.72.",
        prompt: "P(X > 3) is",
        options: ["0.72", "0.28", "0.03", "Cannot tell without the PMF"],
        answer: 1,
        explain: "Tail = 1 − F(3) = **0.28**. You do not need the individual masses.",
        src: "exam",
      },
      {
        id: "18c",
        prompt: "For a continuous RV, P(X < 5) compared with P(X ≤ 5) is",
        options: [
          "Always smaller",
          "Always larger",
          "The same, because P(X = 5) = 0",
          "Equal only if the PDF is symmetric",
        ],
        answer: 2,
        explain: "**The same.** The extra equal sign is a point, and a point has probability zero. Discrete RVs do **not** get this free pass.",
        src: "concept",
      },
    ],
  },
  {
    id: 19,
    pos: 19,
    slug: "continuity-correction",
    tier: 3,
    title: "Continuity correction — binomial through a normal door",
    sub: "The notes bury this under Normal. The paper asks it whenever n is large and they want a probability, not a mean.",
    lastPaper: 1,
    older: 1,
    recipe: "Check np≥5 and nq≥5. μ=np, σ=√(npq). Then bump the integer by 0.5 toward the side you are including.",
    body: [
      {
        type: "p",
        text: "Binomial is a pile of spikes. Normal is a smooth hill. To pretend the pile is the hill, you give each integer a **0.5-wide slab**. That slab is the continuity correction.",
      },
      {
        type: "formula",
        title: "When you are allowed to use it",
        lines: [
          "Need: n large enough that np ≥ 5  AND  nq ≥ 5   (q = 1−p)",
          "Then Y ~ Binomial(n,p)  ≈  X ~ Normal(μ = np,  σ = √(npq))",
        ],
      },
      {
        type: "table",
        headers: ["You want", "Translate to continuous X"],
        rows: [
          ["P(Y ≤ k)", "P(X ≤ k + 0.5)"],
          ["P(Y ≥ k)", "P(X ≥ k − 0.5)"],
          ["P(Y < k)", "P(X ≤ k − 0.5)"],
          ["P(Y > k)", "P(X ≥ k + 0.5)"],
          ["P(Y = k)", "P(k − 0.5 < X < k + 0.5)"],
        ],
      },
      {
        type: "callout",
        kind: "recipe",
        title: "The 0.5 always moves toward the integers you are keeping",
        text: "Including 40 and everything below? The slab for 40 goes up to 40.5. Including 10 and everything above? The slab for 10 starts at 9.5. Draw the spikes, shade the ones you want, then read off the outer edge.",
      },
      {
        type: "callout",
        kind: "example",
        title: "Worked — n=100, p=0.5, P(Y ≤ 40)",
        text: "np = nq = 50 ≥ 5, legal.\nμ = 50, σ = √25 = 5.\nP(Y ≤ 40) ≈ P(X ≤ 40.5).\nz = (40.5 − 50)/5 = −1.90.\nP(Z ≤ −1.90) ≈ **0.0287** (table).\nSkipping the 0.5 uses z = −2.00 and 0.0228 — close, but the paper's range will match 40.5.",
      },
      {
        type: "callout",
        kind: "tip",
        title: "Use the solver, don't hand-roll the 0.5",
        text: "Open **Solve → Normal ≈ binomial** and **Tables** together. The solver applies the 0.5 for you and shows the z.",
      },
    ],
    questions: [
      {
        id: "19a",
        story: "n = 20 trials, p = 0.2.",
        prompt: "Can you approximate this binomial with a normal?",
        options: [
          "Yes — n is bigger than 5",
          "Yes — np = 4 is close enough",
          "No — np = 4, which is less than 5",
          "No — binomial can never be approximated",
        ],
        answer: 2,
        explain: "np = 4 < 5. nq = 16 ≥ 5, but **both** must clear 5. Do not approximate.",
        src: "exam",
      },
      {
        id: "19b",
        story: "Y ~ Binomial(n=100, p=0.5), approximated by a normal.",
        prompt: "P(Y ≤ 40) is rewritten as",
        options: [
          "P(X ≤ 40)",
          "P(X ≤ 40.5)",
          "P(X ≤ 39.5)",
          "P(X ≥ 40.5)",
        ],
        answer: 1,
        explain: "Keeping 40 and everything below. The slab for 40 ends at **40.5**. So P(X ≤ 40.5).",
        src: "exam",
      },
      {
        id: "19c",
        prompt: "P(Y ≥ 10) with a continuity correction becomes",
        options: [
          "P(X ≥ 10.5)",
          "P(X ≥ 10)",
          "P(X ≥ 9.5)",
          "P(X ≤ 9.5)",
        ],
        answer: 2,
        explain: "Keeping 10 and everything above. The slab for 10 starts at **9.5**. So P(X ≥ 9.5).",
        src: "exam",
      },
    ],
  },
];
