import type { Lesson } from "./types";
import { MORE_LESSONS } from "./lessons-rest";

export const LESSONS: Lesson[] = [
  {
    id: 1,
    pos: 1,
    slug: "pass-arithmetic",
    tier: 1,
    title: "Read this first — 10 right out of 20 is all you need",
    sub: "Five minutes. Skip it and everything below is harder.",
    lastPaper: 0,
    older: 0,
    recipe: "10 / 20 = pass. Collect those ten from the four most repetitive machines.",
    body: [
      {
        type: "p",
        text: "This subject is **Business Statistics for Entrepreneurs I** — four modules, from 'what is a variable' to the normal curve. The paper is **20 multiple-choice questions**, each worth 4 or 5 marks, and there is **no partial credit**. Nobody gives you marks for a correct formula with a slipped decimal. Only the letter you circle counts.",
      },
      {
        type: "formula",
        title: "So the entire target is this one number",
        lines: [
          "10 questions right out of 20  =  50%  =  you pass.",
          "Not 20. Not 15. Ten.",
          "Everything on this page is arranged so you collect those ten from the easiest, most repetitive questions — then keep going for cushion.",
        ],
      },
      {
        type: "p",
        text: "There isn't a public last-paper dump for BSE I the way there is for BSE II, so the weightage below is how **this syllabus is actually examined**: they don't ask you to recite definitions. They hand you a small business story, and you plug numbers into one recipe.",
      },
      {
        type: "h",
        text: "The paper is four machines, not four modules",
      },
      {
        type: "table",
        headers: ["The machine", "What the story looks like", "Typical marks"],
        rows: [
          ["Expected value of a table", "values + probabilities, insurance, bets", "2–3"],
          ["Binomial / Bernoulli", "fixed n, success/fail, same p", "2–3"],
          ["Poisson", "count per hour / per metre / per page", "2–3"],
          ["Normal + z", "bell curve, mean and SD given", "2–3"],
          ["Exponential / Uniform", "waiting time, 'equally likely between'", "1–2"],
          ["Linear combo / portfolio", "Y = aX+b, two assets, correlation", "2–3"],
          ["Bayes / conditional", "'given that', a test result", "1–2"],
          ["Descriptive leftovers", "median vs mean, CV, z-outlier, percentile / IQR fences", "2–3"],
        ],
      },
      {
        type: "p",
        text: "Four machines — expected value, binomial, Poisson, normal — are the **minimum path to ten**. Do Lessons 3 through 6 honestly and you can pass. Everything after that is insurance.",
      },
      {
        type: "table",
        headers: ["Time", "Do this", "Running total"],
        rows: [
          ["0–10 min", "This lesson + Lesson 2 (classifier)", "strategy locked"],
          ["10–25 min", "Lesson 3 — expected value", "~2 marks"],
          ["25–55 min", "Lessons 4, 5, 6 — binomial, Poisson, normal", "~8 marks · **past a pass**"],
          ["55–80 min", "Lessons 7–10 — continuous + linear combo + Bayes", "cushion"],
          ["80–120 min", "Lessons 11–19 — the cheap leftovers", "A-range"],
        ],
      },
      {
        type: "callout",
        kind: "tip",
        title: "Use the four buttons in the bottom-right corner",
        text: "**Solve** runs every recipe and shows the working — check your own arithmetic. **Tables** has the z-table. **Calc** is a plain calculator with square-root and x². **Sheet** is every formula on one page. Keep them open the whole time.",
      },
      {
        type: "callout",
        kind: "recipe",
        title: "You are not learning statistics",
        text: "You are learning nine recipes and where to look things up. Two hours, worked honestly, is enough.",
      },
    ],
    questions: [
      {
        id: "1a",
        prompt: "The paper is 20 MCQs at 4–5 marks each with no partial credit. How many questions do you need right to pass at 50%?",
        options: ["5", "10", "15", "All 20"],
        answer: 1,
        explain: "**10 out of 20.** Half the paper. This page is arranged so four machines cover those ten. Everything past that is cushion.",
        src: "concept",
      },
      {
        id: "1b",
        prompt: "A question gives five numbers and asks for the median, and one of the numbers is an obvious outlier. What do you do with the outlier?",
        options: [
          "Drop it, then take the median",
          "Keep it — the median does not care",
          "Replace it with the mean",
          "Report that the median cannot be computed",
        ],
        answer: 1,
        explain: "**Keep it.** Sort, pick the middle. Outliers yank the **mean**. The median sits still. That is the whole point of asking for it.",
        src: "concept",
      },
      {
        id: "1c",
        prompt: "Every option is a range like 'Between 0.30 and 0.36'. What does that mean for your working?",
        options: [
          "You must be exact to 4 decimal places",
          "Rough arithmetic is usually enough to pick the right letter",
          "Always pick the middle option",
          "Ranges mean the question is unanswerable",
        ],
        answer: 1,
        explain: "**Rough is enough.** √16 = 4, e⁻³ is a bit under 0.05, C(5,2)=10. You can often answer in ten seconds without finishing the pretty version of the sum.",
        src: "concept",
      },
    ],
  },
  {
    id: 2,
    pos: 2,
    slug: "pick-the-machine",
    tier: 1,
    title: "The 20-second classifier — which recipe is this?",
    sub: "Zero arithmetic. The mark is already half-won once you name the machine.",
    lastPaper: 2,
    older: 2,
    recipe: "Read the story. Name the distribution. Then open that solver.",
    body: [
      {
        type: "p",
        text: "Most wrong answers on this paper are not bad arithmetic. They are **the right formula for the wrong machine**. A Poisson question treated as binomial. An exponential tail treated as uniform. Thirty seconds of classifying saves four marks.",
      },
      {
        type: "formula",
        title: "The classifier — say it out loud",
        lines: [
          "Are they COUNTING events in a window?          → Poisson",
          "Fixed n trials, success/fail, same p?          → Binomial (n=1 → Bernoulli)",
          "Time until the next event / lifetime?          → Exponential",
          "Any value between L and U equally likely?      → Uniform",
          "Bell curve, mean and SD given, 'approximately'? → Normal",
          "A table of values and probabilities?           → Discrete RV  (use E[X])",
          "Two assets, weights, correlation?              → Portfolio",
          "'Given that' / updated after a test result?    → Conditional / Bayes",
        ],
      },
      {
        type: "table",
        headers: ["Phrase in the question", "Machine"],
        rows: [
          ["customers arriving per hour, defects per metre, emails per day", "Poisson"],
          ["10 independent customers, each buys with p = 0.3", "Binomial"],
          ["time between arrivals, battery life, waiting time", "Exponential"],
          ["delivery equally likely between 2 and 5 days", "Uniform"],
          ["weights, test scores, heights, measurement error", "Normal"],
          ["'at most k' / 'at least k'", "CDF: sum the PMF, or 1 − F(k−1)"],
          ["'given that', 'if we know', 'tested positive'", "Conditional / Bayes"],
        ],
      },
      {
        type: "callout",
        kind: "trap",
        title: "Poisson vs binomial — the one mix-up that costs a mark",
        text: "Binomial has a **ceiling** (you cannot have more successes than trials). Poisson has **no ceiling** — 0, 1, 2, … forever. If the question never gives you n, it is not binomial.",
      },
      {
        type: "callout",
        kind: "tip",
        title: "Exponential and Poisson are the same process, two questions",
        text: "Poisson **counts** events in a fixed interval. Exponential **times** the gap between those events. If arrivals are 6 per hour, the wait is Exponential with λ = 6, mean 1/6 hour.",
      },
    ],
    questions: [
      {
        id: "2a",
        prompt: "A call centre gets 12 calls per hour, on average. The question asks for the probability of 8 calls in the next 30 minutes. Which machine?",
        options: ["Binomial n=12, p=0.5", "Poisson with λ = 6", "Poisson with λ = 12", "Exponential with λ = 12"],
        answer: 1,
        explain: "**Poisson, λ = 6.** Rate is 12 per hour, the window is half an hour, so λ = 12 × 0.5 = 6. Counting events in a window = Poisson. Not binomial — there is no n.",
        src: "exam",
      },
      {
        id: "2b",
        prompt: "A shop has 8 walk-ins this afternoon. Each independently buys with probability 0.25. You want P(exactly 3 buy). Which machine?",
        options: ["Poisson λ = 2", "Binomial n=8, p=0.25", "Bernoulli p=0.25", "Normal μ=2, σ=√1.5"],
        answer: 1,
        explain: "**Binomial.** Fixed n=8, two outcomes, constant p, independent. (Poisson would be the right *approximation* only if n were huge and p tiny, and the question would say so.)",
        src: "exam",
      },
      {
        id: "2c",
        prompt: "Buses arrive as a Poisson process at 4 per hour. The question asks the probability that you wait more than 20 minutes. Which machine?",
        options: [
          "Poisson λ = 4/3",
          "Uniform on [0, 20]",
          "Exponential λ = 4, with x = 1/3 hour",
          "Binomial n=4, p=1/3",
        ],
        answer: 2,
        explain: "**Exponential.** Time until the next event. λ = 4 per hour, x = 20/60 = 1/3 hour, so P(X > 1/3) = e^{−4/3}. Poisson would answer 'how many buses in 20 minutes'.",
        src: "exam",
      },
    ],
  },
  {
    id: 3,
    pos: 3,
    slug: "expected-value",
    tier: 1,
    title: "Expected value — the long-run average machine",
    sub: "If you can do this, insurance, bets, and break-even premiums all collapse to one sum.",
    lastPaper: 3,
    older: 2,
    recipe: "E[X] = Σ x · f(x).   Var(X) = Σ (x − μ)² · f(x).",
    body: [
      {
        type: "p",
        text: "A **random variable** is just a number the experiment spit out. Discrete RVs take countable values (0, 1, 2, …). Continuous ones take any value in an interval. This lesson is the discrete one — a short table of x and f(x).",
      },
      {
        type: "formula",
        title: "The two sums. That is the whole machine.",
        lines: [
          "E[X]  =  Σ  x · f(x)             ← the centre",
          "Var(X) =  Σ  (x − μ)² · f(x)     ← the spread",
          "SD(X)  =  √Var(X)                ← same units as x",
        ],
      },
      {
        type: "p",
        text: "f(x) is the **probability mass function**. Two conditions, always: each f(x) sits in [0, 1], and they **sum to 1**. If a question gives you a broken table, the first check is that sum.",
      },
      {
        type: "callout",
        kind: "example",
        title: "Worked — a food cart's daily refunds",
        text: "Refunds X take values 0, 200, 500 with probabilities 0.7, 0.2, 0.1.\n\nE[X] = 0(0.7) + 200(0.2) + 500(0.1) = 0 + 40 + 50 = **90**.\n\nThat 90 is the break-even number: if you budget ₹90 per day for refunds, you break even in the long run. Some days zero, some days 500 — on average, 90.",
      },
      {
        type: "callout",
        kind: "tip",
        title: "Insurance translation",
        text: "Break-even premium = expected claim amount. Profit sits on top of that. If they ask 'fair premium', they want E[X], not E[X] plus a loading.",
      },
      {
        type: "p",
        text: "The **CDF** F(x) = P(X ≤ x) is the running sum of the PMF. Tail probability: P(X > x) = 1 − F(x). 'At most k' is F(k). 'At least k' is 1 − F(k−1).",
      },
    ],
    questions: [
      {
        id: "3a",
        story: "A stall sells tea. Daily profit X is 100, 200 or 400 with probabilities 0.5, 0.3, 0.2.",
        prompt: "What is E[X]?",
        options: ["200", "180", "190", "230"],
        answer: 2,
        explain: "E[X] = 100(0.5) + 200(0.3) + 400(0.2) = 50 + 60 + 80 = **190**.",
        src: "exam",
      },
      {
        id: "3b",
        story: "A warranty pays ₹0 with probability 0.8, ₹2,000 with probability 0.15, and ₹10,000 with probability 0.05.",
        prompt: "Fair (break-even) premium is closest to",
        options: ["₹400", "₹800", "₹1,200", "₹2,000"],
        answer: 1,
        explain: "E[X] = 0(0.8) + 2000(0.15) + 10000(0.05) = 0 + 300 + 500 = **₹800**. Fair premium = expected claim.",
        src: "exam",
      },
      {
        id: "3c",
        story: "X takes 0, 1, 2 with f(x) = 0.2, 0.5, 0.3. E[X] = 1.1.",
        prompt: "Var(X) is closest to",
        options: ["0.29", "0.49", "0.70", "1.10"],
        answer: 1,
        explain: "(0−1.1)²(0.2) + (1−1.1)²(0.5) + (2−1.1)²(0.3) = 1.21(0.2) + 0.01(0.5) + 0.81(0.3) = 0.242 + 0.005 + 0.243 = **0.49**.",
        src: "exam",
      },
      {
        id: "3d",
        prompt: "A PMF table has f(0)=0.3, f(1)=0.5, f(2)=0.3. Before computing E[X] you should",
        options: [
          "Go ahead — each f(x) is between 0 and 1",
          "Reject it — the masses sum to 1.1, not 1",
          "Divide each mass by 3",
          "Treat it as a PDF",
        ],
        answer: 1,
        explain: "**Sum must be 1.** 0.3+0.5+0.3 = 1.1. The table is broken. First check on every PMF question.",
        src: "concept",
      },
      {
        id: "3e",
        story: "X = 0 or 10 with f(0)=0.9, f(10)=0.1.",
        prompt: "SD(X) is closest to",
        options: ["1", "3", "9", "10"],
        answer: 1,
        explain: "E[X] = 1. Var = (0−1)²(0.9)+(10−1)²(0.1) = 0.9 + 8.1 = 9. SD = **3**.",
        src: "exam",
      },
    ],
  },
  {
    id: 4,
    pos: 4,
    slug: "binomial",
    tier: 1,
    title: "Bernoulli → Binomial — the success-counter",
    sub: "One trial is Bernoulli. n independent copies is Binomial. One PMF.",
    lastPaper: 3,
    older: 3,
    recipe: "P(Y = y) = C(n,y) p^y (1−p)^{n−y}.  Mean np.  SD √(npq).",
    body: [
      {
        type: "p",
        text: "**Bernoulli** is one coin-flip: success (1) with probability p, failure (0) with q = 1−p. Mean p, variance p(1−p). That is the whole distribution — two numbers.",
      },
      {
        type: "p",
        text: "Repeat it **n times**, independently, same p, and count the successes. That count is **Binomial(n, p)**.",
      },
      {
        type: "h",
        text: "Four conditions. If any one fails, it is not binomial.",
      },
      {
        type: "ul",
        items: [
          "**Fixed n** — you know how many trials before you start.",
          "**Two outcomes** per trial — success / failure. (If there are three, stop.)",
          "**Independence** — one trial does not change the next.",
          "**Constant p** — the success chance does not drift.",
        ],
      },
      {
        type: "formula",
        title: "PMF and the three numbers you actually need",
        lines: [
          "P(Y = y) = C(n, y) · p^y · (1−p)^{n−y}",
          "C(n, y) = n! / (y! (n−y)!)",
          "E[Y] = np",
          "Var(Y) = np(1−p)     SD = √(npq)",
        ],
      },
      {
        type: "callout",
        kind: "example",
        title: "Worked — 5 customers, p = 0.4, P(exactly 2 buy)",
        text: "C(5,2) = 10.\n10 × (0.4)² × (0.6)³ = 10 × 0.16 × 0.216 = **0.3456**.\nMean = 5×0.4 = 2.  SD = √(5×0.4×0.6) = √1.2 ≈ 1.10.",
      },
      {
        type: "callout",
        kind: "recipe",
        title: "At most / at least — don't invent a new formula",
        text: "**At most k**  →  P(Y ≤ k) = P(0)+P(1)+…+P(k).\n**At least k**  →  P(Y ≥ k) = 1 − P(Y ≤ k−1).\nOpen the Binomial solver, switch the dropdown, type n, p, y.",
      },
      {
        type: "callout",
        kind: "trap",
        title: "n = 1 is Bernoulli, and that is a real question",
        text: "If they ask for a single yes/no trial, don't reach for the binomial coefficient. P(Y=1) = p. Mean = p. Variance = p(1−p).",
      },
    ],
    questions: [
      {
        id: "4a",
        story: "A cold-email sequence: 6 independent founders, each replies with p = 0.3.",
        prompt: "P(exactly 2 replies) is closest to",
        options: ["0.18", "0.32", "0.42", "0.59"],
        answer: 1,
        explain: "C(6,2)=15. 15 × (0.3)² × (0.7)⁴ = 15 × 0.09 × 0.2401 = 15 × 0.021609 = **0.324**.",
        src: "exam",
      },
      {
        id: "4b",
        story: "Same setup: n = 6, p = 0.3.",
        prompt: "The mean number of replies is",
        options: ["0.3", "1.26", "1.8", "2.0"],
        answer: 2,
        explain: "np = 6 × 0.3 = **1.8**. Do not compute the PMF when they only ask for the mean.",
        src: "exam",
      },
      {
        id: "4c",
        prompt: "A binomial question asks for P(Y ≥ 1) with n = 4, p = 0.2. Fastest correct route?",
        options: [
          "Add P(1)+P(2)+P(3)+P(4)",
          "1 − P(Y = 0)",
          "1 − P(Y = 4)",
          "P(Y = 1) only",
        ],
        answer: 1,
        explain: "**1 − P(0).** 'At least one' is the complement of zero. P(0) = (0.8)⁴ = 0.4096, so P(Y≥1) = 0.5904. Same answer as adding four terms, one line instead of four.",
        src: "concept",
      },
      {
        id: "4d",
        story: "A single yes/no trial with p = 0.7 (Bernoulli).",
        prompt: "Variance is",
        options: ["0.7", "0.21", "0.49", "1"],
        answer: 1,
        explain: "Var = p(1−p) = 0.7×0.3 = **0.21**. Mean is 0.7 — don't mix them.",
        src: "exam",
      },
      {
        id: "4e",
        story: "n = 5, p = 0.4.",
        prompt: "P(Y ≤ 1) equals",
        options: ["P(0)+P(1)", "1 − P(0)", "P(1) only", "P(Y ≥ 1)"],
        answer: 0,
        explain: "**At most 1** = P(0)+P(1). C(5,0)(0.4)⁰(0.6)⁵ + C(5,1)(0.4)¹(0.6)⁴ = 0.07776 + 0.2592 = 0.337.",
        src: "exam",
      },
    ],
  },
  {
    id: 5,
    pos: 5,
    slug: "poisson",
    tier: 1,
    title: "Poisson — counting in a window",
    sub: "Emails per hour. Defects per metre. One parameter. Mean equals variance.",
    lastPaper: 3,
    older: 2,
    recipe: "P(Y = y) = e^{−λ} λ^y / y!.  Scale λ to the window they asked for.",
    body: [
      {
        type: "p",
        text: "Poisson models **how many times something happens** in a fixed interval of time or space. The interval can be an hour, a page, a kilometre of highway. The random variable takes 0, 1, 2, 3, … with no upper cap.",
      },
      {
        type: "formula",
        title: "One parameter. Three properties.",
        lines: [
          "P(Y = y) = e^{−λ} · λ^y / y!     (e ≈ 2.71828)",
          "E[Y] = λ",
          "Var(Y) = λ     SD = √λ",
        ],
      },
      {
        type: "h",
        text: "The only trick: scale λ to the window",
      },
      {
        type: "p",
        text: "λ is the mean count **in the interval they asked about**, not the rate printed in the first sentence. If the rate is 10 per hour and they ask about 2 hours, λ = 20. If they ask about 30 minutes, λ = 5.",
      },
      {
        type: "callout",
        kind: "example",
        title: "Worked — 10 emails/hour, P(none in 12 minutes)",
        text: "12 minutes = 0.2 hours, so λ = 10 × 0.2 = 2.\nP(Y=0) = e^{−2} · 2⁰ / 0! = e^{−2} ≈ **0.1353**.",
      },
      {
        type: "ul",
        items: [
          "Probability of an event in a window depends only on the **length** of the window, not where it starts.",
          "Non-overlapping windows are **independent**.",
          "Inter-arrival times of a Poisson process are **Exponential**.",
        ],
      },
      {
        type: "callout",
        kind: "tip",
        title: "Poisson as a binomial limit",
        text: "When n is large and p is small, with np = λ held fixed, Binomial(n,p) ≈ Poisson(λ). Use this only when the question hints at it, or when n is huge and multiplying (1−p)^{n−y} is ugly.",
      },
    ],
    questions: [
      {
        id: "5a",
        story: "Defects occur at 3 per 10 metres of fabric.",
        prompt: "For a 10-metre roll, P(zero defects) is closest to",
        options: ["0.05", "0.10", "0.22", "0.50"],
        answer: 0,
        explain: "λ = 3. P(Y=0) = e^{−3} ≈ **0.0498**. Between 0.05 on the options.",
        src: "exam",
      },
      {
        id: "5b",
        story: "A store sees 8 customers per hour, Poisson.",
        prompt: "In 15 minutes, the Poisson parameter λ is",
        options: ["8", "4", "2", "0.15"],
        answer: 2,
        explain: "15 minutes = 0.25 hours. λ = 8 × 0.25 = **2**. Always rescale.",
        src: "exam",
      },
      {
        id: "5c",
        prompt: "For Poisson(λ), which statement is always true?",
        options: [
          "Mean is λ, variance is λ²",
          "Mean is λ, variance is λ",
          "Mean is λ, variance is √λ",
          "Mean is nλ, variance is λ",
        ],
        answer: 1,
        explain: "**Mean = variance = λ.** SD is √λ. This is the signature of Poisson — if a question tells you mean 4 and variance 4, they are waving Poisson at you.",
        src: "concept",
      },
      {
        id: "5d",
        story: "Calls arrive at 12 per hour.",
        prompt: "P(exactly 0 calls in 10 minutes) is closest to",
        options: ["0.14", "0.37", "0.50", "e^{−12}"],
        answer: 0,
        explain: "10 min = 1/6 hour, λ = 12 × 1/6 = 2. P(0) = e^{−2} ≈ **0.135**.",
        src: "exam",
      },
      {
        id: "5e",
        prompt: "A Poisson process has mean 4 defects per metre. Over 2 metres, variance of the count is",
        options: ["2", "4", "8", "16"],
        answer: 2,
        explain: "New λ = 4×2 = 8. For Poisson, variance = λ = **8**.",
        src: "exam",
      },
    ],
  },
  {
    id: 6,
    pos: 6,
    slug: "normal",
    tier: 1,
    title: "Normal — standardise, then read the table",
    sub: "Bell curve. z = (x − μ)/σ. 68–95–99.7. That is almost every continuous mark.",
    lastPaper: 3,
    older: 3,
    recipe: "z = (x − μ)/σ.  P(X ≤ x) = P(Z ≤ z). Look it up.",
    body: [
      {
        type: "p",
        text: "The normal curve is symmetric about μ. Mean = median = mode. Total area 1, half the area on each side of the mean. σ stretches the bell — bigger σ, flatter curve.",
      },
      {
        type: "formula",
        title: "The only conversion you need",
        lines: [
          "z  =  (x − μ) / σ",
          "z is 'how many SDs above (or below) the mean'.",
          "Standard normal Z has mean 0 and SD 1.",
        ],
      },
      {
        type: "h",
        text: "Empirical rule — free marks if they ask for 'approximate area'",
      },
      {
        type: "table",
        headers: ["Interval", "Approximate area"],
        rows: [
          ["μ ± 1σ", "68%  (more precisely 68.3%)"],
          ["μ ± 2σ", "95%  (95.4%)"],
          ["μ ± 3σ", "99.7%"],
        ],
      },
      {
        type: "callout",
        kind: "example",
        title: "Worked — delivery times N(40, 5²), P(X < 50)",
        text: "z = (50 − 40)/5 = 2.\nThe middle 95% sits inside μ ± 2σ, so the left tail beyond −2σ is about 2.5% and the right tail beyond +2σ is about 2.5%.\nP(X < μ+2σ) = 0.5 + 0.95/2 ≈ **0.975** (table: 0.9772).",
      },
      {
        type: "h",
        text: "Normal approximation to the binomial",
      },
      {
        type: "p",
        text: "When n is large, Binomial(n,p) looks like Normal(μ = np, σ = √(npq)). Use it only when **np ≥ 5 and nq ≥ 5**. Because binomial is discrete and normal is continuous, apply a **continuity correction**: P(Y ≤ k) ≈ P(X ≤ k + 0.5). Lesson 19 drills the 0.5-bump until it is muscle memory.",
      },
      {
        type: "callout",
        kind: "tip",
        title: "Open TABLES in the corner",
        text: "The z-table on this page is the left-tail P(Z ≤ z). For a right tail, do 1 minus the table value. For a two-sided middle, table(upper) − table(lower).",
      },
    ],
    questions: [
      {
        id: "6a",
        story: "Weekly demand ~ Normal(μ = 200, σ = 20).",
        prompt: "P(demand < 240) is closest to",
        options: ["0.50", "0.68", "0.84", "0.98"],
        answer: 3,
        explain: "z = (240−200)/20 = 2. P(Z<2) ≈ 0.977. Empirical rule: μ+2σ is the top of the middle 95%, so left of it is about **97.7%**.",
        src: "exam",
      },
      {
        id: "6b",
        prompt: "A question says a dataset is 'approximately normal' with mean 50 and SD 10. About what percent of observations sit between 40 and 60?",
        options: ["50%", "68%", "95%", "99.7%"],
        answer: 1,
        explain: "40 and 60 are **μ ± 1σ**. Empirical rule: **~68%**.",
        src: "concept",
      },
      {
        id: "6c",
        story: "n = 100 independent trials, p = 0.5. Someone wants P(Y ≤ 40) using a normal approximation.",
        prompt: "The approximating normal is",
        options: [
          "N(40, 5²)",
          "N(50, 5²)",
          "N(50, 25²)",
          "You cannot approximate — np < 5",
        ],
        answer: 1,
        explain: "μ = np = 50. σ = √(npq) = √25 = 5, so **N(50, 5²)**. np = nq = 50 ≥ 5, approximation is legal. Continuity correction would use 40.5.",
        src: "exam",
      },
      {
        id: "6d",
        story: "X ~ N(100, 15²). Empirical rule.",
        prompt: "About 95% of values sit between",
        options: ["85 and 115", "70 and 130", "55 and 145", "100 and 130"],
        answer: 1,
        explain: "μ ± 2σ = 100 ± 30 = **70 to 130**. 1σ is 68%, 3σ is 99.7%.",
        src: "exam",
      },
      {
        id: "6e",
        story: "z = 1.0. The table gives P(Z ≤ 1) ≈ 0.8413.",
        prompt: "P(Z > 1) is closest to",
        options: ["0.16", "0.32", "0.50", "0.84"],
        answer: 0,
        explain: "Right tail = 1 − 0.8413 ≈ **0.159**. Half the leftover of the 68% middle (16% in each tail of 1σ).",
        src: "exam",
      },
    ],
  },
];

export const ALL_LESSONS: Lesson[] = [...LESSONS, ...MORE_LESSONS];

